/* ==========================================================================
   Racing Hobbies Ecuador — Catálogo de productos
   Inventario real de la tienda (racinghobbies.net). Precios en USD.
   `img` apunta a assets/img/. Editar aquí actualiza todo el sitio.
   ========================================================================== */

const RH_CATEGORIES = Object.freeze([
  { slug: "crawlers", label: "Crawlers 4x4" },
  { slug: "pista", label: "Autos de Pista" },
  { slug: "monster", label: "Monster y Off-Road" },
  { slug: "camiones", label: "Camiones y Trailers" },
  { slug: "aviones", label: "Aviones RC" },
  { slug: "helis", label: "Helicópteros" },
  { slug: "energia", label: "Baterías" },
  { slug: "nitro", label: "Nitro y Repuestos" },
  { slug: "louis", label: "Monomarca Louis" },
]);

const RH_LOUIS_PRODUCTS = Object.freeze([
  {"id":"louis-lnba205","code":"LNBA205","name":"Drive Shaft And Spur Gear Hub (For Gear Diff)","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNBA205.webp","desc":"Drive Shaft And Spur Gear Hub (For Gear Diff)","specs":["Código: LNBA205","Monomarca Louis"]},
  {"id":"louis-lnba206","code":"LNBA206","name":"Carbon Servo Mount Set","cat":"louis","price":25,"tag":null,"img":"assets/img/louis/LNBA206.webp","desc":"Carbon Servo Mount Set","specs":["Código: LNBA206","Monomarca Louis"]},
  {"id":"louis-lnba207","code":"LNBA207","name":"17T Metal Bevel Gear (Gear Diff)","cat":"louis","price":14,"tag":null,"img":"assets/img/louis/LNBA207.webp","desc":"17T Metal Bevel Gear (Gear Diff)","specs":["Código: LNBA207","Monomarca Louis"]},
  {"id":"louis-lnba210","code":"LNBA210","name":"4.8x6mm Ball Stud","cat":"louis","price":9.5,"tag":null,"img":"assets/img/louis/LNBA210.webp","desc":"4.8x6mm Ball Stud","specs":["Código: LNBA210","Monomarca Louis"]},
  {"id":"louis-lnba211","code":"LNBA211","name":"Pivot Ball Stud","cat":"louis","price":9.5,"tag":null,"img":"assets/img/louis/LNBA211.webp","desc":"Pivot Ball Stud","specs":["Código: LNBA211","Monomarca Louis"]},
  {"id":"louis-lnba215","code":"LNBA215","name":"39T-48P Pinon Gear(Aluminum)","cat":"louis","price":12.5,"tag":null,"img":"assets/img/louis/LNBA215.webp","desc":"39T-48P Pinon Gear(Aluminum)","specs":["Código: LNBA215","Monomarca Louis"]},
  {"id":"louis-lnba219","code":"LNBA219","name":"Shock Parts(O-rings)","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNBA219.webp","desc":"Shock Parts(O-rings)","specs":["Código: LNBA219","Monomarca Louis"]},
  {"id":"louis-lnba221","code":"LNBA221","name":"Shock Shafts","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNBA221.webp","desc":"Shock Shafts","specs":["Código: LNBA221","Monomarca Louis"]},
  {"id":"louis-lnba223","code":"LNBA223","name":"Shock Parts","cat":"louis","price":10,"tag":null,"img":"assets/img/louis/LNBA223.webp","desc":"Shock Parts","specs":["Código: LNBA223","Monomarca Louis"]},
  {"id":"louis-lnba225","code":"LNBA225","name":"Shock Spring (1.2X22mm)Blue-Hard","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNBA225.webp","desc":"Shock Spring (1.2X22mm)Blue-Hard","specs":["Código: LNBA225","Monomarca Louis"]},
  {"id":"louis-lnba226","code":"LNBA226","name":"Shock Spring(1.2X22mm)Yellow-Medium","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNBA226.webp","desc":"Shock Spring(1.2X22mm)Yellow-Medium","specs":["Código: LNBA226","Monomarca Louis"]},
  {"id":"louis-lnba227","code":"LNBA227","name":"Shock Spring (1.2X22mm)Red-Soft","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNBA227.webp","desc":"Shock Spring (1.2X22mm)Red-Soft","specs":["Código: LNBA227","Monomarca Louis"]},
  {"id":"louis-lnba230","code":"LNBA230","name":"Gear Differential","cat":"louis","price":48,"tag":null,"img":"assets/img/louis/LNBA230.webp","desc":"Gear Differential","specs":["Código: LNBA230","Monomarca Louis"]},
  {"id":"louis-lnba231","code":"LNBA231","name":"Gear Diff Case","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNBA231.webp","desc":"Gear Diff Case","specs":["Código: LNBA231","Monomarca Louis"]},
  {"id":"louis-lnba232","code":"LNBA232","name":"42T Bevel Gear (Metal)","cat":"louis","price":18,"tag":null,"img":"assets/img/louis/LNBA232.webp","desc":"42T Bevel Gear (Metal)","specs":["Código: LNBA232","Monomarca Louis"]},
  {"id":"louis-lnba233","code":"LNBA233","name":"Gear Diff Cup Joint","cat":"louis","price":15,"tag":null,"img":"assets/img/louis/LNBA233.webp","desc":"Gear Diff Cup Joint","specs":["Código: LNBA233","Monomarca Louis"]},
  {"id":"louis-lnba234","code":"LNBA234","name":"Gear Diff Oring","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNBA234.webp","desc":"Gear Diff Oring","specs":["Código: LNBA234","Monomarca Louis"]},
  {"id":"louis-lnba235","code":"LNBA235","name":"Gear Diff Bevel Gear Set","cat":"louis","price":18,"tag":null,"img":"assets/img/louis/LNBA235.webp","desc":"Gear Diff Bevel Gear Set","specs":["Código: LNBA235","Monomarca Louis"]},
  {"id":"louis-lnba245","code":"LNBA245","name":"Front Bumper Hold And Body Mount","cat":"louis","price":10,"tag":null,"img":"assets/img/louis/LNBA245.webp","desc":"Front Bumper Hold And Body Mount","specs":["Código: LNBA245","Monomarca Louis"]},
  {"id":"louis-lnba249","code":"LNBA249","name":"Gear Box","cat":"louis","price":18,"tag":null,"img":"assets/img/louis/LNBA249.webp","desc":"Gear Box","specs":["Código: LNBA249","Monomarca Louis"]},
  {"id":"louis-lnba252","code":"LNBA252","name":"Spur Gear 72T","cat":"louis","price":7,"tag":null,"img":"assets/img/louis/LNBA252.webp","desc":"Spur Gear 72T","specs":["Código: LNBA252","Monomarca Louis"]},
  {"id":"louis-lnba254","code":"LNBA254","name":"Servo Saver","cat":"louis","price":16,"tag":null,"img":"assets/img/louis/LNBA254.webp","desc":"Servo Saver","specs":["Código: LNBA254","Monomarca Louis"]},
  {"id":"louis-lnba255","code":"LNBA255","name":"Cup Jiont","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNBA255.webp","desc":"Cup Jiont","specs":["Código: LNBA255","Monomarca Louis"]},
  {"id":"louis-lnba256","code":"LNBA256","name":"Bumper For Sedan Body","cat":"louis","price":7,"tag":null,"img":"assets/img/louis/LNBA256.webp","desc":"Bumper For Sedan Body","specs":["Código: LNBA256","Monomarca Louis"]},
  {"id":"louis-lnba257","code":"LNBA257","name":"Bumper For Hatchback Body","cat":"louis","price":7,"tag":null,"img":"assets/img/louis/LNBA257.webp","desc":"Bumper For Hatchback Body","specs":["Código: LNBA257","Monomarca Louis"]},
  {"id":"louis-lnba258","code":"LNBA258","name":"Battery Strap","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA258.webp","desc":"Battery Strap","specs":["Código: LNBA258","Monomarca Louis"]},
  {"id":"louis-lnba274","code":"LNBA274","name":"Carbon Battery Holder","cat":"louis","price":12,"tag":null,"img":"assets/img/louis/LNBA274.webp","desc":"Carbon Battery Holder","specs":["Código: LNBA274","Monomarca Louis"]},
  {"id":"louis-lnba275","code":"LNBA275","name":"Carbon Body Mount Plate","cat":"louis","price":16,"tag":null,"img":"assets/img/louis/LNBA275.webp","desc":"Carbon Body Mount Plate","specs":["Código: LNBA275","Monomarca Louis"]},
  {"id":"louis-lnba278","code":"LNBA278","name":"Bumper Plate (For Sedan Body)","cat":"louis","price":10,"tag":null,"img":"assets/img/louis/LNBA278.webp","desc":"Bumper Plate (For Sedan Body)","specs":["Código: LNBA278","Monomarca Louis"]},
  {"id":"louis-lnba279","code":"LNBA279","name":"Screw Set - FH M3x6","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA279.webp","desc":"Screw Set - FH M3x6","specs":["Código: LNBA279","Monomarca Louis"]},
  {"id":"louis-lnba280","code":"LNBA280","name":"Screw Set - FH M3x8","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA280.webp","desc":"Screw Set - FH M3x8","specs":["Código: LNBA280","Monomarca Louis"]},
  {"id":"louis-lnba281","code":"LNBA281","name":"Screw Set - BH M3x6","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA281.webp","desc":"Screw Set - BH M3x6","specs":["Código: LNBA281","Monomarca Louis"]},
  {"id":"louis-lnba282","code":"LNBA282","name":"Screw Set - BH M3x8","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA282.webp","desc":"Screw Set - BH M3x8","specs":["Código: LNBA282","Monomarca Louis"]},
  {"id":"louis-lnba283","code":"LNBA283","name":"Screw Set - BH M3x10","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA283.webp","desc":"Screw Set - BH M3x10","specs":["Código: LNBA283","Monomarca Louis"]},
  {"id":"louis-lnba284","code":"LNBA284","name":"Screw Set - BH M3x12","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA284.webp","desc":"Screw Set - BH M3x12","specs":["Código: LNBA284","Monomarca Louis"]},
  {"id":"louis-lnba285","code":"LNBA285","name":"Screw Set - BH M3x18","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA285.webp","desc":"Screw Set - BH M3x18","specs":["Código: LNBA285","Monomarca Louis"]},
  {"id":"louis-lnba286","code":"LNBA286","name":"Screw Set - FH M2x8","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNBA286.webp","desc":"Screw Set - FH M2x8","specs":["Código: LNBA286","Monomarca Louis"]},
  {"id":"louis-lnba287","code":"LNBA287","name":"Set Screw M3x3","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA287.webp","desc":"Set Screw M3x3","specs":["Código: LNBA287","Monomarca Louis"]},
  {"id":"louis-lnba288","code":"LNBA288","name":"Set Screw M3x4","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA288.webp","desc":"Set Screw M3x4","specs":["Código: LNBA288","Monomarca Louis"]},
  {"id":"louis-lnba289","code":"LNBA289","name":"Set Screw M3x8","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA289.webp","desc":"Set Screw M3x8","specs":["Código: LNBA289","Monomarca Louis"]},
  {"id":"louis-lnba290","code":"LNBA290","name":"Set Screw M3x10","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA290.webp","desc":"Set Screw M3x10","specs":["Código: LNBA290","Monomarca Louis"]},
  {"id":"louis-lnba291","code":"LNBA291","name":"Set Screw M3x12","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA291.webp","desc":"Set Screw M3x12","specs":["Código: LNBA291","Monomarca Louis"]},
  {"id":"louis-lnba292","code":"LNBA292","name":"Set Screw M3x18","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNBA292.webp","desc":"Set Screw M3x18","specs":["Código: LNBA292","Monomarca Louis"]},
  {"id":"louis-lnba293","code":"LNBA293","name":"Set Screw M3x20","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNBA293.webp","desc":"Set Screw M3x20","specs":["Código: LNBA293","Monomarca Louis"]},
  {"id":"louis-lnba294","code":"LNBA294","name":"M3 Nut","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA294.webp","desc":"M3 Nut","specs":["Código: LNBA294","Monomarca Louis"]},
  {"id":"louis-lnba295","code":"LNBA295","name":"M4 Nut","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNBA295.webp","desc":"M4 Nut","specs":["Código: LNBA295","Monomarca Louis"]},
  {"id":"louis-lnba297","code":"LNBA297","name":"Bearing5*8*2.5","cat":"louis","price":7,"tag":null,"img":"assets/img/louis/LNBA297.webp","desc":"Bearing5*8*2.5","specs":["Código: LNBA297","Monomarca Louis"]},
  {"id":"louis-lnba298","code":"LNBA298","name":"Bearing 5X10X4","cat":"louis","price":13,"tag":null,"img":"assets/img/louis/LNBA298.webp","desc":"Bearing 5X10X4","specs":["Código: LNBA298","Monomarca Louis"]},
  {"id":"louis-lnba299","code":"LNBA299","name":"Bearing 10X15X4","cat":"louis","price":13,"tag":null,"img":"assets/img/louis/LNBA299.webp","desc":"Bearing 10X15X4","specs":["Código: LNBA299","Monomarca Louis"]},
  {"id":"louis-lnba301","code":"LNBA301","name":"Washer(3*6.5*0.5mm )","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA301.webp","desc":"Washer(3*6.5*0.5mm )","specs":["Código: LNBA301","Monomarca Louis"]},
  {"id":"louis-lnba302","code":"LNBA302","name":"Washer(3*8*0.5mm )","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA302.webp","desc":"Washer(3*8*0.5mm )","specs":["Código: LNBA302","Monomarca Louis"]},
  {"id":"louis-lnba303","code":"LNBA303","name":"E-Clip","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNBA303.webp","desc":"E-Clip","specs":["Código: LNBA303","Monomarca Louis"]},
  {"id":"louis-lnba304","code":"LNBA304","name":"Pin 2X10","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNBA304.webp","desc":"Pin 2X10","specs":["Código: LNBA304","Monomarca Louis"]},
  {"id":"louis-lnba306","code":"LNBA306","name":"O-Ring","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNBA306.webp","desc":"O-Ring","specs":["Código: LNBA306","Monomarca Louis"]},
  {"id":"louis-lnba307","code":"LNBA307","name":"Washer(11*14*0.2mm )","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNBA307.webp","desc":"Washer(11*14*0.2mm )","specs":["Código: LNBA307","Monomarca Louis"]},
  {"id":"louis-lnba310","code":"LNBA310","name":"Gear Differential Set","cat":"louis","price":60,"tag":null,"img":"assets/img/louis/LNBA310.webp","desc":"Gear Differential Set","specs":["Código: LNBA310","Monomarca Louis"]},
  {"id":"louis-lnba312","code":"LNBA312","name":"Fan Holder(For 30mm Fan)","cat":"louis","price":15,"tag":null,"img":"assets/img/louis/LNBA312.webp","desc":"Fan Holder(For 30mm Fan)","specs":["Código: LNBA312","Monomarca Louis"]},
  {"id":"louis-lnba313","code":"LNBA313","name":"Pivot Block Toe In 3° (Aluminum)","cat":"louis","price":20,"tag":null,"img":"assets/img/louis/LNBA313.webp","desc":"Pivot Block Toe In 3° (Aluminum)","specs":["Código: LNBA313","Monomarca Louis"]},
  {"id":"louis-lnba314","code":"LNBA314","name":"Pivot Block Toe In 0° (Aluminum)","cat":"louis","price":20,"tag":null,"img":"assets/img/louis/LNBA314.webp","desc":"Pivot Block Toe In 0° (Aluminum)","specs":["Código: LNBA314","Monomarca Louis"]},
  {"id":"louis-lnba315","code":"LNBA315","name":"Pivot Block Toe In 2.5° (Aluminum)","cat":"louis","price":20,"tag":null,"img":"assets/img/louis/LNBA315.webp","desc":"Pivot Block Toe In 2.5° (Aluminum)","specs":["Código: LNBA315","Monomarca Louis"]},
  {"id":"louis-lnba318","code":"LNBA318","name":"Aluminum Hex 5.5x10mm","cat":"louis","price":13,"tag":null,"img":"assets/img/louis/LNBA318.webp","desc":"Aluminum Hex 5.5x10mm","specs":["Código: LNBA318","Monomarca Louis"]},
  {"id":"louis-lnba325","code":"LNBA325","name":"42T Metal Bevel Gear (For Solid Axle)","cat":"louis","price":18,"tag":null,"img":"assets/img/louis/LNBA325.webp","desc":"42T Metal Bevel Gear (For Solid Axle)","specs":["Código: LNBA325","Monomarca Louis"]},
  {"id":"louis-lnba327","code":"LNBA327","name":"Metal Center Cup Joint(For Gear Diff)","cat":"louis","price":15,"tag":null,"img":"assets/img/louis/LNBA327.webp","desc":"Metal Center Cup Joint(For Gear Diff)","specs":["Código: LNBA327","Monomarca Louis"]},
  {"id":"louis-lnba332","code":"LNBA332","name":"Strong Ball End 4.8mm(4Pcs)","cat":"louis","price":6,"tag":null,"img":"assets/img/louis/LNBA332.webp","desc":"Strong Ball End 4.8mm(4Pcs)","specs":["Código: LNBA332","Monomarca Louis"]},
  {"id":"louis-lnba334","code":"LNBA334","name":"Strong Ball End 4.8mm-Long (4Pcs)","cat":"louis","price":6,"tag":null,"img":"assets/img/louis/LNBA334.webp","desc":"Strong Ball End 4.8mm-Long (4Pcs)","specs":["Código: LNBA334","Monomarca Louis"]},
  {"id":"louis-lnba336","code":"LNBA336","name":"Bumper For Touring Car Body","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNBA336.webp","desc":"Bumper For Touring Car Body","specs":["Código: LNBA336","Monomarca Louis"]},
  {"id":"louis-lnba337","code":"LNBA337","name":"Bumper Plate&Body Post Spacer(Plastic)","cat":"louis","price":6,"tag":null,"img":"assets/img/louis/LNBA337.webp","desc":"Bumper Plate&Body Post Spacer(Plastic)","specs":["Código: LNBA337","Monomarca Louis"]},
  {"id":"louis-lnba338","code":"LNBA338","name":"Pivot Block Toe In 2° (Aluminum)","cat":"louis","price":20,"tag":null,"img":"assets/img/louis/LNBA338.webp","desc":"Pivot Block Toe In 2° (Aluminum)","specs":["Código: LNBA338","Monomarca Louis"]},
  {"id":"louis-lnba342","code":"LNBA342","name":"Body Post (Rear)","cat":"louis","price":7,"tag":null,"img":"assets/img/louis/LNBA342.webp","desc":"Body Post (Rear)","specs":["Código: LNBA342","Monomarca Louis"]},
  {"id":"louis-lnba343","code":"LNBA343","name":"12mm Hex Hub(6mm)","cat":"louis","price":23,"tag":null,"img":"assets/img/louis/LNBA343.webp","desc":"12mm Hex Hub(6mm)","specs":["Código: LNBA343","Monomarca Louis"]},
  {"id":"louis-lnba344","code":"LNBA344","name":"12mm Hex Hub(7mm)","cat":"louis","price":23,"tag":null,"img":"assets/img/louis/LNBA344.webp","desc":"12mm Hex Hub(7mm)","specs":["Código: LNBA344","Monomarca Louis"]},
  {"id":"louis-lnba346","code":"LNBA346","name":"Aluminum Spacer 3x6x0.5(8 PCS)","cat":"louis","price":6,"tag":null,"img":"assets/img/louis/LNBA346.webp","desc":"Aluminum Spacer 3x6x0.5(8 PCS)","specs":["Código: LNBA346","Monomarca Louis"]},
  {"id":"louis-lnba347","code":"LNBA347","name":"Aluminum Spacer 3x6x1(8 PCS)","cat":"louis","price":6,"tag":null,"img":"assets/img/louis/LNBA347.webp","desc":"Aluminum Spacer 3x6x1(8 PCS)","specs":["Código: LNBA347","Monomarca Louis"]},
  {"id":"louis-lnba348","code":"LNBA348","name":"Aluminum Spacer 3x6x2(8 PCS)","cat":"louis","price":7,"tag":null,"img":"assets/img/louis/LNBA348.webp","desc":"Aluminum Spacer 3x6x2(8 PCS)","specs":["Código: LNBA348","Monomarca Louis"]},
  {"id":"louis-lnba349","code":"LNBA349","name":"Aluminum Spacer 3x6x3(8 PCS)","cat":"louis","price":7,"tag":null,"img":"assets/img/louis/LNBA349.webp","desc":"Aluminum Spacer 3x6x3(8 PCS)","specs":["Código: LNBA349","Monomarca Louis"]},
  {"id":"louis-lnba350","code":"LNBA350","name":"Aluminum Spacer 3x6x4(8 PCS)","cat":"louis","price":7,"tag":null,"img":"assets/img/louis/LNBA350.webp","desc":"Aluminum Spacer 3x6x4(8 PCS)","specs":["Código: LNBA350","Monomarca Louis"]},
  {"id":"louis-lnba356","code":"LNBA356","name":"Extended Body Post(6mm)","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNBA356.webp","desc":"Extended Body Post(6mm)","specs":["Código: LNBA356","Monomarca Louis"]},
  {"id":"louis-lnba357","code":"LNBA357","name":"Gear Diff Cup Joint(Heavy Duty)","cat":"louis","price":20,"tag":null,"img":"assets/img/louis/LNBA357.webp","desc":"Gear Diff Cup Joint(Heavy Duty)","specs":["Código: LNBA357","Monomarca Louis"]},
  {"id":"louis-lnba360","code":"LNBA360","name":"Spur Gear 68T(Heavy Duty Steel)","cat":"louis","price":25,"tag":null,"img":"assets/img/louis/LNBA360.webp","desc":"Spur Gear 68T(Heavy Duty Steel)","specs":["Código: LNBA360","Monomarca Louis"]},
  {"id":"louis-lnba361","code":"LNBA361","name":"CVD Pin (4Pcs)","cat":"louis","price":6,"tag":null,"img":"assets/img/louis/LNBA361.webp","desc":"CVD Pin (4Pcs)","specs":["Código: LNBA361","Monomarca Louis"]},
  {"id":"louis-lnba362","code":"LNBA362","name":"Shock Spacer(4pcs)","cat":"louis","price":7,"tag":null,"img":"assets/img/louis/LNBA362.webp","desc":"Shock Spacer(4pcs)","specs":["Código: LNBA362","Monomarca Louis"]},
  {"id":"louis-lnba363","code":"LNBA363","name":"Shcok Pistons-3H 1.2","cat":"louis","price":7.5,"tag":null,"img":"assets/img/louis/LNBA363.webp","desc":"Shcok Pistons-3H 1.2","specs":["Código: LNBA363","Monomarca Louis"]},
  {"id":"louis-lnba369","code":"LNBA369","name":"Battery Holder","cat":"louis","price":20,"tag":null,"img":"assets/img/louis/LNBA369.webp","desc":"Battery Holder","specs":["Código: LNBA369","Monomarca Louis"]},
  {"id":"louis-lnba370","code":"LNBA370","name":"Diff Bevel Gear","cat":"louis","price":12,"tag":null,"img":"assets/img/louis/LNBA370.webp","desc":"Diff Bevel Gear","specs":["Código: LNBA370","Monomarca Louis"]},
  {"id":"louis-lnba372","code":"LNBA372","name":"Rally Tires+Wheels 10 Spoke Black +1mm (4PCS)","cat":"louis","price":25,"tag":null,"img":"assets/img/louis/LNBA372.webp","desc":"Rally Tires+Wheels 10 Spoke Black +1mm (4PCS)","specs":["Código: LNBA372","Monomarca Louis"]},
  {"id":"louis-lnba373","code":"LNBA373","name":"Rear Gear Shaft Cup Joint & Gear Hub","cat":"louis","price":14,"tag":null,"img":"assets/img/louis/LNBA373.webp","desc":"Rear Gear Shaft Cup Joint & Gear Hub","specs":["Código: LNBA373","Monomarca Louis"]},
  {"id":"louis-lnba383","code":"LNBA383","name":"LMX Bumper/Small","cat":"louis","price":10,"tag":null,"img":"assets/img/louis/LNBA383.webp","desc":"LMX Bumper/Small","specs":["Código: LNBA383","Monomarca Louis"]},
  {"id":"louis-lnba384","code":"LNBA384","name":"LMX Bumper/Medium","cat":"louis","price":10,"tag":null,"img":"assets/img/louis/LNBA384.webp","desc":"LMX Bumper/Medium","specs":["Código: LNBA384","Monomarca Louis"]},
  {"id":"louis-lnba389","code":"LNBA389","name":"Diff Gasket (4PCS)","cat":"louis","price":6,"tag":null,"img":"assets/img/louis/LNBA389.webp","desc":"Diff Gasket (4PCS)","specs":["Código: LNBA389","Monomarca Louis"]},
  {"id":"louis-lnba390","code":"LNBA390","name":"CNC Delrin Spur Gear 60T","cat":"louis","price":25,"tag":null,"img":"assets/img/louis/LNBA390.webp","desc":"CNC Delrin Spur Gear 60T","specs":["Código: LNBA390","Monomarca Louis"]},
  {"id":"louis-lnba391","code":"LNBA391","name":"CNC Delrin Spur Gear 65T","cat":"louis","price":25,"tag":null,"img":"assets/img/louis/LNBA391.webp","desc":"CNC Delrin Spur Gear 65T","specs":["Código: LNBA391","Monomarca Louis"]},
  {"id":"louis-lnba807","code":"LNBA807","name":"MCL-F1 Clean Body (210~225mm)","cat":"louis","price":45,"tag":null,"img":"assets/img/louis/LNBA807.webp","desc":"MCL-F1 Clean Body (210~225mm)","specs":["Código: LNBA807","Monomarca Louis"]},
  {"id":"louis-lnba809","code":"LNBA809","name":"M-Racing Truck (210mm)","cat":"louis","price":55,"tag":null,"img":"assets/img/louis/LNBA809.webp","desc":"M-Racing Truck (210mm)","specs":["Código: LNBA809","Monomarca Louis"]},
  {"id":"louis-lnha102","code":"LNHA102","name":"LTX 1/10 Touring Car","cat":"louis","price":350,"tag":null,"img":"assets/img/louis/LNHA102.webp","desc":"LTX 1/10 Touring Car","specs":["Código: LNHA102","Monomarca Louis"]},
  {"id":"louis-lnha105","code":"LNHA105","name":"LRX 1/10 Rally Car","cat":"louis","price":380,"tag":null,"img":"assets/img/louis/LNHA105.webp","desc":"LRX 1/10 Rally Car","specs":["Código: LNHA105","Monomarca Louis"]},
  {"id":"louis-lnha402","code":"LNHA402","name":"Arm Set(F&R)","cat":"louis","price":17,"tag":null,"img":"assets/img/louis/LNHA402.webp","desc":"Arm Set(F&R)","specs":["Código: LNHA402","Monomarca Louis"]},
  {"id":"louis-lnha403","code":"LNHA403","name":"C Hub(R/L)","cat":"louis","price":10,"tag":null,"img":"assets/img/louis/LNHA403.webp","desc":"C Hub(R/L)","specs":["Código: LNHA403","Monomarca Louis"]},
  {"id":"louis-lnha404","code":"LNHA404","name":"Hub Carrier","cat":"louis","price":10,"tag":null,"img":"assets/img/louis/LNHA404.webp","desc":"Hub Carrier","specs":["Código: LNHA404","Monomarca Louis"]},
  {"id":"louis-lnha405","code":"LNHA405","name":"Suspension Mount Parts","cat":"louis","price":12,"tag":null,"img":"assets/img/louis/LNHA405.webp","desc":"Suspension Mount Parts","specs":["Código: LNHA405","Monomarca Louis"]},
  {"id":"louis-lnha406","code":"LNHA406","name":"Steering Track","cat":"louis","price":11,"tag":null,"img":"assets/img/louis/LNHA406.webp","desc":"Steering Track","specs":["Código: LNHA406","Monomarca Louis"]},
  {"id":"louis-lnha410","code":"LNHA410","name":"Front Bumper Holder Set","cat":"louis","price":15,"tag":null,"img":"assets/img/louis/LNHA410.webp","desc":"Front Bumper Holder Set","specs":["Código: LNHA410","Monomarca Louis"]},
  {"id":"louis-lnha412","code":"LNHA412","name":"Bumper","cat":"louis","price":10,"tag":null,"img":"assets/img/louis/LNHA412.webp","desc":"Bumper","specs":["Código: LNHA412","Monomarca Louis"]},
  {"id":"louis-lnha413","code":"LNHA413","name":"Center Drive Shaft","cat":"louis","price":16,"tag":null,"img":"assets/img/louis/LNHA413.webp","desc":"Center Drive Shaft","specs":["Código: LNHA413","Monomarca Louis"]},
  {"id":"louis-lnha414","code":"LNHA414","name":"CVD Drive Shaft","cat":"louis","price":26,"tag":null,"img":"assets/img/louis/LNHA414.webp","desc":"CVD Drive Shaft","specs":["Código: LNHA414","Monomarca Louis"]},
  {"id":"louis-lnha417","code":"LNHA417","name":"Turnbuckle Set","cat":"louis","price":13,"tag":null,"img":"assets/img/louis/LNHA417.webp","desc":"Turnbuckle Set","specs":["Código: LNHA417","Monomarca Louis"]},
  {"id":"louis-lnha419","code":"LNHA419","name":"Steeing Bush","cat":"louis","price":9,"tag":null,"img":"assets/img/louis/LNHA419.webp","desc":"Steeing Bush","specs":["Código: LNHA419","Monomarca Louis"]},
  {"id":"louis-lnha420","code":"LNHA420","name":"Ball Stud / 4.8x9mm","cat":"louis","price":9,"tag":null,"img":"assets/img/louis/LNHA420.webp","desc":"Ball Stud / 4.8x9mm","specs":["Código: LNHA420","Monomarca Louis"]},
  {"id":"louis-lnha422","code":"LNHA422","name":"Steering Post","cat":"louis","price":14,"tag":null,"img":"assets/img/louis/LNHA422.webp","desc":"Steering Post","specs":["Código: LNHA422","Monomarca Louis"]},
  {"id":"louis-lnha423","code":"LNHA423","name":"Suspension Shaft Set","cat":"louis","price":12,"tag":null,"img":"assets/img/louis/LNHA423.webp","desc":"Suspension Shaft Set","specs":["Código: LNHA423","Monomarca Louis"]},
  {"id":"louis-lnha424","code":"LNHA424","name":"Cap Head Screw M2x6 (10PCS)","cat":"louis","price":7,"tag":null,"img":"assets/img/louis/LNHA424.webp","desc":"Cap Head Screw M2x6 (10PCS)","specs":["Código: LNHA424","Monomarca Louis"]},
  {"id":"louis-lnha425","code":"LNHA425","name":"Cap Head Screw M3x6 (10PCS)","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNHA425.webp","desc":"Cap Head Screw M3x6 (10PCS)","specs":["Código: LNHA425","Monomarca Louis"]},
  {"id":"louis-lnha426","code":"LNHA426","name":"Cap Head Screw M3x8 (10PCS)","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNHA426.webp","desc":"Cap Head Screw M3x8 (10PCS)","specs":["Código: LNHA426","Monomarca Louis"]},
  {"id":"louis-lnha427","code":"LNHA427","name":"Cap Head Screw M3x10 (10PCS)","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNHA427.webp","desc":"Cap Head Screw M3x10 (10PCS)","specs":["Código: LNHA427","Monomarca Louis"]},
  {"id":"louis-lnha428","code":"LNHA428","name":"Flat Head Screw M3x14 (10PCS)","cat":"louis","price":5,"tag":null,"img":"assets/img/louis/LNHA428.webp","desc":"Flat Head Screw M3x14 (10PCS)","specs":["Código: LNHA428","Monomarca Louis"]},
  {"id":"louis-lnha431","code":"LNHA431","name":"Carbon Chassis","cat":"louis","price":60,"tag":null,"img":"assets/img/louis/LNHA431.webp","desc":"Carbon Chassis","specs":["Código: LNHA431","Monomarca Louis"]},
  {"id":"louis-lnha432","code":"LNHA432","name":"Carbon Upper Deck","cat":"louis","price":30,"tag":null,"img":"assets/img/louis/LNHA432.webp","desc":"Carbon Upper Deck","specs":["Código: LNHA432","Monomarca Louis"]},
  {"id":"louis-lnha433","code":"LNHA433","name":"Shock Tower","cat":"louis","price":20,"tag":null,"img":"assets/img/louis/LNHA433.webp","desc":"Shock Tower","specs":["Código: LNHA433","Monomarca Louis"]},
  {"id":"louis-lnha434","code":"LNHA434","name":"Sway Bar-1.4mm","cat":"louis","price":11.5,"tag":null,"img":"assets/img/louis/LNHA434.webp","desc":"Sway Bar-1.4mm","specs":["Código: LNHA434","Monomarca Louis"]},
  {"id":"louis-lnha435","code":"LNHA435","name":"Sway Bar-1.6mm","cat":"louis","price":12,"tag":null,"img":"assets/img/louis/LNHA435.webp","desc":"Sway Bar-1.6mm","specs":["Código: LNHA435","Monomarca Louis"]},
  {"id":"louis-lnha438","code":"LNHA438","name":"Wing Set","cat":"louis","price":15,"tag":null,"img":"assets/img/louis/LNHA438.webp","desc":"Wing Set","specs":["Código: LNHA438","Monomarca Louis"]},
  {"id":"louis-lnha439","code":"LNHA439","name":"Back Millor And Exhaust Pipe","cat":"louis","price":10,"tag":null,"img":"assets/img/louis/LNHA439.webp","desc":"Back Millor And Exhaust Pipe","specs":["Código: LNHA439","Monomarca Louis"]},
  {"id":"louis-lnha442","code":"LNHA442","name":"5x7x0.5mm Washer (10 pcs)","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNHA442.webp","desc":"5x7x0.5mm Washer (10 pcs)","specs":["Código: LNHA442","Monomarca Louis"]},
  {"id":"louis-lnha443","code":"LNHA443","name":"5x7x0.2mm Washer (10 pcs)","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNHA443.webp","desc":"5x7x0.2mm Washer (10 pcs)","specs":["Código: LNHA443","Monomarca Louis"]},
  {"id":"louis-lnha447","code":"LNHA447","name":"Aluminum Rear Hub","cat":"louis","price":50,"tag":null,"img":"assets/img/louis/LNHA447.webp","desc":"Aluminum Rear Hub","specs":["Código: LNHA447","Monomarca Louis"]},
  {"id":"louis-lnha448","code":"LNHA448","name":"Aluminum Steering Blocks","cat":"louis","price":55,"tag":null,"img":"assets/img/louis/LNHA448.webp","desc":"Aluminum Steering Blocks","specs":["Código: LNHA448","Monomarca Louis"]},
  {"id":"louis-lnha449","code":"LNHA449","name":"Aluminum C Hub(L/R)","cat":"louis","price":55,"tag":null,"img":"assets/img/louis/LNHA449.webp","desc":"Aluminum C Hub(L/R)","specs":["Código: LNHA449","Monomarca Louis"]},
  {"id":"louis-lnha453","code":"LNHA453","name":"Steering Set(AL)","cat":"louis","price":50,"tag":null,"img":"assets/img/louis/LNHA453.webp","desc":"Steering Set(AL)","specs":["Código: LNHA453","Monomarca Louis"]},
  {"id":"louis-lnha457","code":"LNHA457","name":"Shock spring (1.4X20) White","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNHA457.webp","desc":"Shock spring (1.4X20) White","specs":["Código: LNHA457","Monomarca Louis"]},
  {"id":"louis-lnha459","code":"LNHA459","name":"Shock spring (1.4X20) Yellow","cat":"louis","price":8,"tag":null,"img":"assets/img/louis/LNHA459.webp","desc":"Shock spring (1.4X20) Yellow","specs":["Código: LNHA459","Monomarca Louis"]},
  {"id":"louis-lnha475","code":"LNHA475","name":"Heavy Duty Gear Diff Set","cat":"louis","price":35,"tag":null,"img":"assets/img/louis/LNHA475.webp","desc":"Heavy Duty Gear Diff Set","specs":["Código: LNHA475","Monomarca Louis"]},
  {"id":"louis-lnha483","code":"LNHA483","name":"Carbon Steering Brace","cat":"louis","price":13,"tag":null,"img":"assets/img/louis/LNHA483.webp","desc":"Carbon Steering Brace","specs":["Código: LNHA483","Monomarca Louis"]},
  {"id":"louis-lnha484","code":"LNHA484","name":"1/10 DRIFT TIRES (4PCS)","cat":"louis","price":15,"tag":null,"img":"assets/img/louis/LNHA484.webp","desc":"1/10 DRIFT TIRES (4PCS)","specs":["Código: LNHA484","Monomarca Louis"]},
  {"id":"louis-lnha485","code":"LNHA485","name":"1/10 Rally Tires 6 Spoke Wheel-Black /ET-0mm(4PCS)","cat":"louis","price":28,"tag":null,"img":"assets/img/louis/LNHA485.webp","desc":"1/10 Rally Tires 6 Spoke Wheel-Black /ET-0mm(4PCS)","specs":["Código: LNHA485","Monomarca Louis"]},
  {"id":"louis-lnha491","code":"LNHA491","name":"1/10 Rally Tires 26mm(4PCS)","cat":"louis","price":15,"tag":null,"img":"assets/img/louis/LNHA491.webp","desc":"1/10 Rally Tires 26mm(4PCS)","specs":["Código: LNHA491","Monomarca Louis"]},
  {"id":"louis-lnha519","code":"LNHA519","name":"Carbon Bearing holder plate","cat":"louis","price":12,"tag":null,"img":"assets/img/louis/LNHA519.webp","desc":"Carbon Bearing holder plate","specs":["Código: LNHA519","Monomarca Louis"]},
  {"id":"louis-lnha549","code":"LNHA549","name":"Washer(3x5x0.5mm )","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNHA549.webp","desc":"Washer(3x5x0.5mm )","specs":["Código: LNHA549","Monomarca Louis"]},
  {"id":"louis-lnha550","code":"LNHA550","name":"Washer(3x5x0.2mm )","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNHA550.webp","desc":"Washer(3x5x0.2mm )","specs":["Código: LNHA550","Monomarca Louis"]},
  {"id":"louis-lnha551","code":"LNHA551","name":"Pin(2x7.6mm )","cat":"louis","price":4,"tag":null,"img":"assets/img/louis/LNHA551.webp","desc":"Pin(2x7.6mm )","specs":["Código: LNHA551","Monomarca Louis"]},
  {"id":"louis-lpga-4835","code":"LPGA-4835","name":"35T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","cat":"louis","price":12,"tag":null,"img":"assets/img/louis/LPGA-4835.webp","desc":"35T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","specs":["Código: LPGA-4835","Monomarca Louis"]},
  {"id":"louis-lpga-4836","code":"LPGA-4836","name":"36T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","cat":"louis","price":12,"tag":null,"img":"assets/img/louis/LPGA-4836.webp","desc":"36T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","specs":["Código: LPGA-4836","Monomarca Louis"]},
  {"id":"louis-lpga-4837","code":"LPGA-4837","name":"37T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","cat":"louis","price":12,"tag":null,"img":"assets/img/louis/LPGA-4837.webp","desc":"37T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","specs":["Código: LPGA-4837","Monomarca Louis"]},
  {"id":"louis-lpga-4838","code":"LPGA-4838","name":"38T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","cat":"louis","price":12,"tag":null,"img":"assets/img/louis/LPGA-4838.webp","desc":"38T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","specs":["Código: LPGA-4838","Monomarca Louis"]},
  {"id":"louis-lpga-4840","code":"LPGA-4840","name":"40T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","cat":"louis","price":14,"tag":null,"img":"assets/img/louis/LPGA-4840.webp","desc":"40T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","specs":["Código: LPGA-4840","Monomarca Louis"]},
  {"id":"louis-lpga-4841","code":"LPGA-4841","name":"41T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","cat":"louis","price":10,"tag":null,"img":"assets/img/louis/LPGA-4841.webp","desc":"41T-48P PINION GEAR  AL-7075 / 48 PITCH / HOLE 3.175mm","specs":["Código: LPGA-4841","Monomarca Louis"]},
  {"id":"louis-lxb001","code":"LXB001","name":"Black Nockel Plating-Carten series screw box(160 PCS)","cat":"louis","price":35,"tag":null,"img":"assets/img/louis/sin-imagen.webp","desc":"Black Nockel Plating-Carten series screw box(160 PCS)","specs":["Código: LXB001","Monomarca Louis"]},
  {"id":"louis-lxb004","code":"LXB004","name":"Black Nickel Plating-Universal RC Car Screw Kit For 1/10(230 PCS)","cat":"louis","price":40,"tag":null,"img":"assets/img/louis/sin-imagen.webp","desc":"Black Nickel Plating-Universal RC Car Screw Kit For 1/10(230 PCS)","specs":["Código: LXB004","Monomarca Louis"]},
].map((product) => Object.freeze({ ...product, imageSurface: "photo" })));

const RH_IMAGE_SURFACES = Object.freeze(["photo", "cutout"]);

const RH_PRODUCTS = Object.freeze([
  /* ---------- Crawlers 4x4 ---------- */
  {
    id: "camel-defender",
    name: "Land Rover Camel Trophy Defender 1/10",
    cat: "crawlers",
    price: 710,
    imageSurface: "photo",
    tag: "top",
    img: "assets/img/camel-defender.webp",
    desc: "El icónico Defender de las expediciones Camel Trophy en escala 1/10: tracción 4x4, detalle extremo y capacidad real para superar cualquier terreno.",
    specs: ["Escala 1/10, 4x4", "Edición Camel Trophy", "Listo para correr (RTR)", "Detalle de expedición realista"],
  },
  {
    id: "camel-discovery",
    name: "Land Rover Camel Trophy Discovery 1/10",
    cat: "crawlers",
    price: 710,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/camel-discovery.webp",
    desc: "Crawler de estilo clásico con tracción 4x4, detalles fieles al Discovery original y desempeño sobresaliente en rutas difíciles.",
    specs: ["Escala 1/10, 4x4", "Edición Camel Trophy", "Listo para correr (RTR)", "Carrocería de alto detalle"],
  },
  {
    id: "toyota-land-cruiser",
    name: "FMS Toyota Land Cruiser 1/10",
    cat: "crawlers",
    price: 650,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/toyota-land-cruiser.webp",
    desc: "Crawler altamente detallado con tracción 4x4, acabado realista y excelente rendimiento off-road.",
    specs: ["Escala 1/10, 4x4", "Acabado premium FMS", "Listo para correr (RTR)", "Excelente en terreno difícil"],
  },
  {
    id: "toyota-fj40",
    name: "FMS Toyota FJ40 1/10",
    cat: "crawlers",
    price: 650,
    imageSurface: "photo",
    tag: "top",
    img: "assets/img/toyota-fj40.webp",
    desc: "Un clásico legendario hecho crawler: servo en el volante, sistema completo de luces y detalle de museo.",
    specs: ["Escala 1/10, 4x4", "Sistema de luces completo", "Servo en el volante", "Diseño icónico FJ40"],
  },
  {
    id: "everest-ascent",
    name: "Redcat Everest Ascent 1/10",
    cat: "crawlers",
    price: 580,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/everest-ascent.webp",
    desc: "Todoterreno de alto rendimiento con chasis resistente, tracción 4x4 y gran capacidad de ascenso en terrenos extremos.",
    specs: ["Escala 1/10, 4x4", "Chasis de alto rendimiento", "Gran ángulo de ascenso", "Listo para correr (RTR)"],
  },
  {
    id: "everest-gen7",
    name: "Redcat Everest Gen7 Sport 1/10",
    cat: "crawlers",
    price: 425,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/everest-gen7.webp",
    desc: "Crawler eléctrico con chasis de acero, suspensión de 4 brazos y gran ángulo de articulación para lo más extremo.",
    specs: ["Escala 1/10, 4x4", "Chasis de acero", "Suspensión de 4 brazos", "Listo para correr (RTR)"],
  },
  {
    id: "landrover-series2",
    name: "FMS Land Rover Series II 1/12",
    cat: "crawlers",
    price: 350,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/landrover-series2.webp",
    desc: "Crawler 1/12 detallado con tracción 4x4: potente y portátil para jugarlo dentro y fuera de casa.",
    specs: ["Escala 1/12, 4x4", "Compacto y portátil", "Alto detalle FMS", "Interior y exterior"],
  },
  {
    id: "k5-blazer",
    name: "FMS Chevrolet K5 Blazer 1/24",
    cat: "crawlers",
    price: 250,
    imageSurface: "photo",
    tag: "nuevo",
    availability: "agotado",
    img: "assets/img/k5-blazer.webp",
    desc: "Crawler 2 en 1 con tracción 4x4: conviértelo de camioneta a blazer cuando quieras.",
    specs: ["Escala 1/24, 4x4", "Convertible 2 en 1", "Alto detalle", "Ideal para interiores"],
  },
  {
    id: "lc80-v2",
    name: "FMS Toyota LC80 V2 1/18",
    cat: "crawlers",
    price: 265,
    imageSurface: "photo",
    tag: null,
    availability: "agotado",
    img: "assets/img/lc80-v2.webp",
    desc: "Crawler altamente detallado con tracción 4x4, ejes metálicos y sistema de luces.",
    specs: ["Escala 1/18, 4x4", "Ejes metálicos", "Sistema de luces", "Listo para correr (RTR)"],
  },
  {
    id: "defender-124",
    name: "FMS Land Rover Defender 1/24",
    cat: "crawlers",
    price: 230,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/defender-124.webp",
    desc: "El Defender en formato bolsillo: tracción 4x4, acabado realista y gran desempeño en miniatura.",
    specs: ["Escala 1/24, 4x4", "Alto detalle", "Portátil", "Listo para correr (RTR)"],
  },
  {
    id: "discovery-124",
    name: "FMS Land Rover Discovery 1/24",
    cat: "crawlers",
    price: 230,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/discovery-124.webp",
    desc: "Crawler compacto con tracción 4x4 y acabado realista, listo para la aventura en cualquier lugar.",
    specs: ["Escala 1/24, 4x4", "Alto detalle", "Portátil", "Listo para correr (RTR)"],
  },
  {
    id: "redcat-ascent-118",
    name: "Redcat Ascent 1/18",
    cat: "crawlers",
    price: 220,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/redcat-ascent-118.webp",
    desc: "Crawler escala 1/18 con tracción total 4x4: potente y portátil para jugarlo dentro y fuera de casa.",
    specs: ["Escala 1/18, 4x4", "Tracción total", "Compacto", "Listo para correr (RTR)"],
  },
  {
    id: "wendigo",
    name: "Redcat Wendigo Builders Kit",
    cat: "crawlers",
    price: 425,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/wendigo.webp",
    desc: "Kit de montaje tipo rock racer: chasis metálico, suspensión ajustable y transmisión 4WD. Para armadores de verdad.",
    specs: ["Kit de ensamblaje", "Chasis metálico", "Suspensión ajustable", "Requiere electrónica y motor"],
  },

  /* ---------- Autos de Pista (Tamiya TT-02) ---------- */
  {
    id: "lancia-delta",
    name: "Tamiya Lancia Delta Integrale TT-02",
    cat: "pista",
    price: 300,
    tag: "top",
    imageSurface: "cutout",
    img: "assets/img/lancia-delta.webp",
    desc: "Leyenda del rally sobre chasis TT-02 4WD: suspensión independiente, diferenciales y carrocería de alta precisión.",
    specs: ["Escala 1/10, chasis TT-02 4WD", "Suspensión independiente", "Diferencial delantero/trasero", "Carrocería de alta precisión"],
  },
  {
    id: "golf-gti",
    name: "Tamiya VW Golf II GTI 16V Rally",
    cat: "pista",
    price: 311,
    tag: null,
    imageSurface: "cutout",
    img: "assets/img/golf-gti.webp",
    desc: "El Golf II GTI de rally sobre TT-02 4WD: rendimiento preciso y estable en pistas RC.",
    specs: ["Escala 1/10, chasis TT-02 4WD", "Suspensión independiente", "Carrocería GTI 16V Rally", "Preciso y estable"],
  },
  {
    id: "mercedes-190e",
    name: "Tamiya Mercedes-Benz 190E EVO II",
    cat: "pista",
    price: 300,
    tag: null,
    availability: "agotado",
    imageSurface: "cutout",
    img: "assets/img/mercedes-190e.webp",
    desc: "La bestia del DTM sobre chasis TT-02 4WD con geometría optimizada para pista.",
    specs: ["Escala 1/10, chasis TT-02 4WD", "Suspensión independiente", "Geometría optimizada", "Carrocería EVO II"],
  },
  {
    id: "subaru-impreza",
    name: "Tamiya Subaru Impreza Monte-Carlo '99",
    cat: "pista",
    price: 300,
    tag: null,
    availability: "agotado",
    imageSurface: "cutout",
    img: "assets/img/subaru-impreza.webp",
    desc: "El Impreza del Monte-Carlo '99: chasis TT-02 4WD con ajustes de altura y distancia entre ejes, para asfalto y tierra.",
    specs: ["Escala 1/10, chasis TT-02 4WD", "Ajuste de altura", "Distancia entre ejes ajustable", "Asfalto y tierra"],
  },
  {
    id: "mercedes-c11",
    name: "Tamiya Mercedes-Benz C11 1990",
    cat: "pista",
    price: 280,
    tag: null,
    availability: "agotado",
    imageSurface: "cutout",
    img: "assets/img/mercedes-c11.webp",
    desc: "Prototipo de resistencia con chasis rígido de composite, bañera de resina ABS y suspensión independiente.",
    specs: ["Escala 1/10", "Chasis composite rígido", "Suspensión independiente", "Carrocería detallada"],
  },
  {
    id: "toyota-toms",
    name: "Tamiya Toyota Tom's 84C",
    cat: "pista",
    price: 225,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/toyota-toms.webp",
    desc: "Fiel al prototipo de resistencia de 1984, sobre chasis TT-02 4WD con suspensión independiente.",
    specs: ["Escala 1/10, chasis TT-02 4WD", "Suspensión independiente", "Réplica del 84C de 1984", "Para pista"],
  },

  /* ---------- Monster y Off-Road ---------- */
  {
    id: "tmaxx",
    name: "Traxxas T-Maxx Nitro 4WD",
    cat: "monster",
    price: 800,
    imageSurface: "photo",
    tag: "top",
    img: "assets/img/tmaxx.webp",
    desc: "El rey del nitro: arranque eléctrico EZ-Start®, radio TQ 2.4 GHz, transmisión de 2 velocidades y 8 amortiguadores Ultra Shocks.",
    specs: ["Monster truck nitro 4WD", "Arranque eléctrico EZ-Start®", "Transmisión 2 velocidades", "Suspensión de 4\" con 8 amortiguadores"],
  },
  {
    id: "ridgerunner",
    name: "Redcat RidgeRunner 1/10",
    cat: "monster",
    price: 350,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/ridgerunner.webp",
    desc: "Buggy rápido y resistente con tracción 4x4, suspensión de alto recorrido y gran estabilidad off-road.",
    specs: ["Escala 1/10, 4x4", "Suspensión de alto recorrido", "Gran estabilidad", "Listo para correr (RTR)"],
  },
  {
    id: "volcano-epx",
    name: "Redcat Volcano EPX 4WD",
    cat: "monster",
    price: 380,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/volcano-epx.webp",
    desc: "Monster truck eléctrico 4WD con motor brushed 540 y neumáticos de alto agarre para todo terreno.",
    specs: ["Monster truck 4WD", "Motor brushed 540", "Listo para correr (RTR)", "Neumáticos de alto agarre"],
  },
  {
    id: "mt18",
    name: "Redcat MT-18 Monster Truck 1/18",
    cat: "monster",
    price: 225,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/mt18.webp",
    desc: "Monster truck compacto listo para correr, con neumáticos de gran agarre y chasis resistente.",
    specs: ["Escala 1/18, 4WD", "Listo para correr (RTR)", "Chasis resistente", "Azul y rojo disponibles"],
  },
  {
    id: "volcano-16",
    name: "Redcat Volcano 16 1/16",
    cat: "monster",
    price: 190,
    imageSurface: "photo",
    tag: "oferta",
    img: "assets/img/volcano-16.webp",
    desc: "La puerta de entrada al off-road: monster 4WD eléctrico escala 1/16 listo para correr.",
    specs: ["Escala 1/16, 4WD", "Motor brushed", "Listo para correr (RTR)", "Rojo y azul disponibles"],
  },
  {
    id: "excavadora",
    name: "Excavadora Caterpillar RC 1/24",
    cat: "monster",
    price: 200,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/excavadora.webp",
    desc: "Totalmente funcional y fuerte para trabajos de construcción a escala.",
    specs: ["Escala 1/24", "Totalmente funcional", "Brazo articulado", "Construcción a escala"],
  },

  /* ---------- Camiones y Trailers (Tamiya 1:14) ---------- */
  {
    id: "grand-hauler",
    name: "Tamiya Grand Hauler 1/14",
    cat: "camiones",
    price: 700,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/grand-hauler.webp",
    desc: "Tráiler RC de alto detalle: chasis metálico, suspensión de ballestas y cabina personalizable.",
    specs: ["Escala 1/14", "Chasis metálico", "Suspensión de ballestas", "Cabina personalizable"],
  },
  {
    id: "fuel-tank-trailer",
    name: "Tamiya Fuel Tank Trailer 1/14",
    cat: "camiones",
    price: 700,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/fuel-tank-trailer.webp",
    desc: "Remolque cisterna a escala 1:14 con chasis metálico y componentes en aluminio pulido, para complementar la serie de camiones RC Tamiya.",
    specs: ["Escala 1/14", "Chasis metálico", "Aluminio pulido", "Compatible serie Tamiya"],
  },
  {
    id: "tamiya-mfc-tractor",
    name: "Tamiya Tractor Truck — Unidad Multifunción",
    cat: "camiones",
    price: 800,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/tamiya-mfc-tractor.webp",
    desc: "Unidad multifunción Tamiya para camiones RC: control de sonido, vibración, luces y señales para los modelos Tractor Truck a escala 1:14.",
    specs: ["Sonido de motor y claxon", "Luces y señales", "Vibración realista", "Camiones Tamiya 1:14"],
  },
  {
    id: "tamiya-mfc-02",
    name: "Tamiya MFC-02 — Pick-Up Truck",
    cat: "camiones",
    price: 800,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/tamiya-mfc-02.webp",
    desc: "Unidad multifunción MFC-02 para Pick-Up Truck RC: luces, sonidos de motor, claxon, sirena y efectos realistas a escala 1:14.",
    specs: ["Luces y sirena", "Sonidos de motor y claxon", "Efectos realistas", "Escala 1:14"],
  },

  /* ---------- Aviones RC ---------- */
  {
    id: "tiger-moth",
    name: "Tiger Moth 20cc",
    cat: "aviones",
    price: 850,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/tiger-moth.webp",
    desc: "Biplano de alto rendimiento con motor 20 cc y estructura resistente, optimizado para acrobacias, loops y vuelo rápido.",
    specs: ["Motor 20 cc", "Estructura reforzada", "Acrobacias y loops", "Vuelo en exteriores"],
  },
  {
    id: "f4-phantom",
    name: "F-4 Phantom 32 DF Jet",
    cat: "aviones",
    price: 596,
    imageSurface: "photo",
    tag: "top",
    img: "assets/img/f4-phantom.webp",
    desc: "Jet RC con turbina ducted fan, fuselaje aerodinámico y alto rendimiento para vuelo deportivo.",
    specs: ["Jet con ducted fan", "Fuselaje aerodinámico", "Alto rendimiento", "Vuelo deportivo"],
  },
  {
    id: "edge-as3x",
    name: "BNF AS3X Edge S40",
    cat: "aviones",
    price: 500,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/edge-as3x.webp",
    desc: "Acrobático de alto rendimiento con estabilización AS3X, listo para volar con precisión y control avanzado.",
    specs: ["Estabilización AS3X", "Diseño acrobático", "Control avanzado", "Bind-N-Fly (BNF)"],
  },
  {
    id: "t28-trojan",
    name: "T-28 Trojan",
    cat: "aviones",
    price: 490,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/t28-trojan.webp",
    desc: "El clásico entrenador militar de ala baja con tren de aterrizaje retráctil, ideal para maniobras avanzadas.",
    specs: ["Entrenador militar clásico", "Ala baja", "Tren retráctil", "Maniobras avanzadas"],
  },
  {
    id: "ultra-stick",
    name: "Ultra Stick 10cc",
    cat: "aviones",
    price: 475,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/ultra-stick.webp",
    desc: "Ala alta con motor 10 cc, diseñado para vuelo acrobático y rendimiento avanzado en exteriores.",
    specs: ["Motor 10 cc", "Ala alta", "Vuelo acrobático", "Exteriores"],
  },
  {
    id: "convergence-vtol",
    name: "Convergence VTOL FPV",
    cat: "aviones",
    price: 465,
    imageSurface: "photo",
    tag: "nuevo",
    img: "assets/img/convergence-vtol.webp",
    desc: "Híbrido de ala fija y multirrotor: despegue vertical, transición automática y compatibilidad FPV.",
    specs: ["Despegue vertical (VTOL)", "Transición automática", "Compatible FPV", "Ala fija + multirrotor"],
  },
  {
    id: "ranger-v2",
    name: "FMS Ranger V2 RTF",
    cat: "aviones",
    price: 285,
    imageSurface: "photo",
    tag: "nuevo",
    availability: "agotado",
    img: "assets/img/ranger-v2.webp",
    desc: "El avión ideal para empezar: estable, resistente y listo para volar, con despegue corto y control suave.",
    specs: ["Listo para volar (RTF)", "Ideal principiantes", "Despegue corto", "Vuelo estable"],
  },
  {
    id: "stryker",
    name: "F27Q Stryker",
    cat: "aviones",
    price: 230,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/stryker.webp",
    desc: "Ala voladora ágil y resistente, ideal para combates simulados y vuelo dinámico de alto rendimiento.",
    specs: ["Ala voladora", "Ágil y resistente", "Vuelo dinámico", "Alto rendimiento"],
  },
  {
    id: "night-vapor",
    name: "UMX Night Vapor",
    cat: "aviones",
    price: 175,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/night-vapor.webp",
    desc: "Ultraligero para vuelo en interiores con capacidades acrobáticas precisas y luces para volar de noche.",
    specs: ["Ultraligero de interior", "Luces para vuelo nocturno", "Acrobacias precisas", "Vuelo lento y controlado"],
  },
  {
    id: "arf-beast-60",
    name: "ARF Beast 60s",
    cat: "aviones",
    price: 600,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/arf-beast-60.webp",
    desc: "Biplano acrobático a escala para motor glow o eléctrico, con estructura ligera de madera y diseño ARF de fácil ensamblaje.",
    specs: ["Biplano acrobático", "Glow o eléctrico", "Estructura de madera", "ARF, casi listo para volar"],
  },
  {
    id: "umx-fpv-vapor",
    name: "E-flite UMX FPV Vapor",
    cat: "aviones",
    price: 770,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/umx-fpv-vapor.webp",
    desc: "Avión ultramicro para vuelo en interiores con sistema FPV, ultraligero y estable para maniobras precisas en espacios reducidos.",
    specs: ["Ultramicro UMX", "Compatible FPV", "Vuelo interior", "Ultraligero y estable"],
  },
  {
    id: "hh-mini-vapor",
    name: "HobbyZone Mini Vapor",
    cat: "aviones",
    price: 145,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/hh-mini-vapor.webp",
    desc: "Avión de 338 mm de envergadura y solo 12,5 g, con motor sin escobillas de 17.000 Kv, ideal para vuelo interior y acrobacias precisas.",
    specs: ["Envergadura 338 mm", "Peso 12,5 g", "Motor brushless 17.000 Kv", "Vuelo interior acrobático"],
  },
  {
    id: "stryker-180",
    name: "E-flite F-27Q Stryker 180",
    cat: "aviones",
    price: 150,
    imageSurface: "photo",
    tag: null,
    availability: "agotado",
    img: "assets/img/stryker-180.webp",
    desc: "Ala delta de combate ligera y ágil en maniobras, diseñada para vuelos deportivos y simulaciones tácticas realistas.",
    specs: ["Ala delta de combate", "Ágil y rápido", "Ligero y resistente", "Vuelo deportivo"],
  },

  /* ---------- Helicópteros ---------- */
  {
    id: "blade-150fx",
    name: "Blade 150 FX",
    cat: "helis",
    price: 170,
    imageSurface: "photo",
    tag: "top",
    availability: "agotado",
    img: "assets/img/blade-150fx.webp",
    desc: "Helicóptero listo para volar con excelente estabilidad, rotor de paso fijo y fácil manejo.",
    specs: ["Listo para volar (RTF)", "Rotor de paso fijo", "Excelente estabilidad", "Fácil manejo"],
  },
  {
    id: "blade-mcx2",
    name: "Blade MCX2",
    cat: "helis",
    price: 130,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/blade-mcx2.webp",
    desc: "Helicóptero listo para volar, económico y de altas prestaciones. Perfecto para empezar.",
    specs: ["Listo para volar (RTF)", "Ideal principiantes", "Vuelo en interiores", "Económico"],
  },

  /* ---------- Baterías ---------- */
  {
    id: "hexfly-lipo-3s",
    name: "Hexfly LiPo 3S 11.1V 5000mAh 30C",
    cat: "energia",
    price: 145,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/lipo-hexfly-3s.webp",
    desc: "Energía de competencia para exprimir tu RC: 5000mAh de capacidad con descarga 30C constante.",
    specs: ["11.1V, 3S", "5000 mAh", "Descarga 30C", "Máximo rendimiento"],
  },
  {
    id: "eflite-lipo-4s",
    name: "E-flite LiPo 4S 14.8V 2800mAh 30C",
    cat: "energia",
    price: 60,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/lipo-eflite-4s.webp",
    desc: "Batería potente 4S ideal para máximo rendimiento en aviones y helicópteros RC.",
    specs: ["14.8V, 4S", "2800 mAh", "Descarga 30C", "Ideal para vuelo RC"],
  },
  {
    id: "hexfly-nimh-7s",
    name: "Hexfly NiMh 7S 8.4V 3000mAh",
    cat: "energia",
    price: 55,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/nimh-hexfly.webp",
    desc: "Batería NiMh confiable de 3000mAh, ideal para autos RC eléctricos de uso intensivo.",
    specs: ["8.4V, 7S", "3000 mAh", "Química NiMh", "Uso intensivo"],
  },
  {
    id: "powerhobby-lipo-3s",
    name: "Powerhobby LiPo 3S 11.1V 1300mAh 120C",
    cat: "energia",
    price: 35,
    imageSurface: "photo",
    tag: "oferta",
    img: "assets/img/lipo-powerhobby-3s.webp",
    desc: "Descarga brutal de 120C en formato compacto: punch inmediato para tu RC.",
    specs: ["11.1V, 3S", "1300 mAh", "Descarga 120C", "Formato compacto"],
  },

  /* ---------- Nitro y Repuestos ---------- */
  {
    id: "nitro-kit",
    name: "Nitro Kit All-in-One Redcat",
    cat: "nitro",
    price: 45,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/nitro-kit.webp",
    desc: "Kit completo para carros a nitro: 2 llaves, chispero, cargador, bote y destornilladores.",
    specs: ["Kit completo nitro", "Chispero + cargador", "Llaves y destornilladores", "Todo en uno"],
  },
  {
    id: "nitro-merlin",
    name: "Combustible Merlin Nitro 2.5L",
    cat: "nitro",
    price: 44,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/nitro-merlin.webp",
    desc: "Combustible nitro de alta calidad en presentación de 2.5 litros para motores de combustión interna.",
    specs: ["2.5 litros", "Alta calidad", "Para motores nitro", "Rendimiento constante"],
  },
  {
    id: "glow-plug",
    name: "Bujías Racer Edge Glow",
    cat: "nitro",
    price: 15,
    imageSurface: "photo",
    tag: null,
    img: "assets/img/glow-plug.webp",
    desc: "Las mejores bujías para carros con motor de combustión interna (nitro).",
    specs: ["Bujía glow", "Encendido confiable", "Para motores nitro", "Larga duración"],
  },
  ...RH_LOUIS_PRODUCTS,
].map((product) => {
  if (!RH_IMAGE_SURFACES.includes(product.imageSurface)) {
    throw new Error(
      `Producto ${product.id} debe declarar imageSurface como "photo" o "cutout".`
    );
  }
  return product;
}));
